name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: |
        cd ./src/WebApiBolierplate
        dotnet restore
    - name: Build
      run: |
        cd ./src/WebApiBolierplate
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd ./src/WebApiBolierplate
        dotnet test .\Core.Test\Core.Test.csproj
    - name: IntelliCode Team Completions
      uses: microsoft/vs-intellicode@v1.0
